-- 프로젝트명 : PROJECT_HELLOMOVIE
-- DB 접속 (아이디 : C##HELLO, 비밀번호 : MOVIE)
      -- 테이블 생성

-- 회원 테이블
CREATE TABLE MEMBER(
    MEMBER_CODE NUMBER UNIQUE NOT NULL,
    ID VARCHAR(30) PRIMARY KEY, --아이디
    PWD VARCHAR(70) NOT NULL, --비밀번호
    NAME VARCHAR(10) NOT NULL, --이름
    EMAIL VARCHAR(30) NOT NULL, --이메일
    CONTACT VARCHAR(20) NOT NULL, --연락처
    BIRTH DATE NOT NULL, --생년월일
    MEMBERSHIP VARCHAR(10) NOT NULL, --회원등급
    IDENTIFY NUMBER, --인증여부(Y/N)
    REGDATE DATE NOT NULL--가입날짜
);

 --회원 코드 시퀀스
CREATE SEQUENCE MEMBER_SEQ;

--영화 테이블 생성
CREATE TABLE MOVIE(
    MOVIE_CODE VARCHAR(20) PRIMARY KEY,--영화코드
    CATEGORY VARCHAR(10) NOT NULL, --분류
    GENRE VARCHAR(15) NOT NULL,  --장르
    DIRECTOR VARCHAR(20) NOT NULL, --감독
    ACTOR VARCHAR(20), --출연배우
    MOVIE_AGE NUMBER(3) NOT NULL, --시청연령(등급)    
    D_DAY VARCHAR(10),--개봉일
    SUMMARY VARCHAR(500), --줄거리
    MOVIE_TITLE VARCHAR(50) NOT NULL, --영화제목
    MOVIE_IMG VARCHAR(30) NOT NULL,
    MOVIE_SOLID NUMBER,
    MOVIE_PRICE	NUMBER --영화가격
);


--QNA 테이블 생성
CREATE TABLE QNA(
    QNA_CODE NUMBER PRIMARY KEY, --공지사항 번호
    ID VARCHAR(30), -- 관리자
    QNA_DATE DATE NOT NULL,-- 작성일자
    QNA_TITLE VARCHAR(30) NOT NULL,-- 공지사항
    ADMIN_CONTENT VARCHAR(500) NOT NULL ,-- 공지내용   
    QNA_ANSWER VARCHAR(500),
    FOREIGN KEY (ID) REFERENCES MEMBER(ID)
);

-- QNA 시퀀스
CREATE SEQUENCE QNA_SEQ;

-- 영화 리뷰 테이블
CREATE TABLE REVIEW(
    REVIEW_CODE NUMBER PRIMARY KEY, --댓글 번호
    MOVIE_CODE VARCHAR(20) NOT NULL,
    ID VARCHAR(30) NOT NULL, --작성자
    REVIEW_DATE DATE NOT NULL, --작성일자
    REVIEW_STAR NUMBER NOT NULL, --평점
    REVIEW_CONTENT VARCHAR(500), --내용
    FOREIGN KEY (ID) REFERENCES MEMBER(ID),--회원리뷰
    FOREIGN KEY (MOVIE_CODE) REFERENCES MOVIE(MOVIE_CODE)
);

-- 리뷰 테이블 시퀀스
CREATE SEQUENCE REVIEW_SEQ;

-- 시청내역 테이블
CREATE TABLE HISTORY(
    HISTORY_CODE NUMBER PRIMARY KEY, -- 시청내역
    ID VARCHAR(30) NOT NULL,  --아이디(회원,운영자)
    MOVIE_CODE VARCHAR(20) NOT NULL, --영화코드
    FOREIGN KEY(ID) REFERENCES MEMBER(ID) ON DELETE CASCADE,
    FOREIGN KEY(MOVIE_CODE) REFERENCES MOVIE(MOVIE_CODE)
);

-- 히스토리 시퀀스
CREATE SEQUENCE HISTORY_SEQ;

-- 장바구니 테이블 생성
CREATE TABLE BUCKET(
    BUCKET_CODE NUMBER PRIMARY KEY, --장바구니 번호
    ID VARCHAR(30) NOT NULL, --아이디
    MOVIE_CODE VARCHAR(20) NOT NULL, --영화코드
    FOREIGN KEY(ID) REFERENCES MEMBER(ID) ON DELETE CASCADE,
    FOREIGN KEY(MOVIE_CODE) REFERENCES MOVIE(MOVIE_CODE) ON DELETE CASCADE
);


-- 장바구니 테이블 시퀀스
CREATE SEQUENCE BUCKET_SEQ;

-- 공지사항 테이블
CREATE TABLE NOTICE(
    NOTICE_CODE NUMBER PRIMARY KEY,
    NOTICE_DATE DATE NOT NULL, 
    NOTICE_TITLE VARCHAR(50) NOT NULL,
    NOTICE_CONTENT VARCHAR(500) NOT NULL
);

-- 공지사항 테이블 시퀀스
CREATE SEQUENCE NOTICE_SEQ;

CREATE TABLE BUY(
 BUY_CODE NUMBER PRIMARY KEY,
 BUY_DATE DATE NOT NULL ,
 ID VARCHAR(30) NOT NULL,
 MOVIE_CODE VARCHAR(20) NOT NULL,
 FOREIGN KEY (ID) REFERENCES MEMBER(ID) ON DELETE CASCADE,
 FOREIGN KEY (MOVIE_CODE) REFERENCES MOVIE (MOVIE_CODE)
);

CREATE SEQUENCE BUY_SEQ;


COMMIT;


-- 테이블 삭제(외래키로 연동..관계 보고 하위부터 삭제 )
DROP TABLE NOTICE;
DROP TABLE BUCKET;
DROP TABLE HISTORY;
DROP TABLE REVIEW;
DROP TABLE MEMBER;
DROP TABLE ADMIN;
DROP TABLE BUY;
DROP TABLE MOVIE;
DROP TABLE QNA;
